on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: stepanpopov/rabbit_hole
    steps:
      - uses: actions/checkout@v2
      - run: bash linters.sh

  build:
    runs-on: ubuntu-latest
    container: stepanpopov/rabbit_hole
    needs: [check]
    steps:
      - uses: actions/checkout@v2
      - run: bash build.sh

  test:
    runs-on: ubuntu-latest
    container: stepanpopov/rabbit_hole
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - run: |
          bash build.sh
          bash test.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./build/report
